// swift-tools-version:5.9
// GENERATED by the Veyra SDK release train (version 1.0.16) — do not edit here;
// the source of truth is swift/Package.swift in the SDK monorepo.
// Veyra SDK — public iOS API: pure-Swift facades over the precompiled VeyraKMP core.
import PackageDescription

let package = Package(
    name: "VeyraSDK",
    platforms: [
        // Floor = iOS 15: CoreNFC tag reading is solid from 15, and the supported device
        // floor is iPhone 7 / iOS 15.8. Raising this cuts consuming apps off that device.
        .iOS(.v15)
    ],
    products: [
        // Combined: one dependency line, everything transitively.
        .library(name: "VeyraSDK", targets: ["VeyraSDK"]),
        // Standalone offerings (mirror the Android co.veyra:softpos-sdk / co.veyra:wallet-sdk).
        .library(name: "VeyraSoftPOS", targets: ["VeyraSoftPOS"]),
        .library(name: "VeyraWallet", targets: ["VeyraWallet"]),
    ],
    targets: [
        // The precompiled shared core every product builds on.
        .binaryTarget(
            name: "VeyraKMP",
            url: "https://repo.veyra.co/releases/files/VeyraKMP-1.0.16.xcframework.zip",
            checksum: "1e584bd9b3c57d9fa7dc9d3f55eb349f42ad846dcf05de441b9babfbd5684fcc"
        ),
        .target(name: "VeyraSoftPOS", dependencies: ["VeyraKMP"]),
        .target(name: "VeyraWallet", dependencies: ["VeyraKMP"]),
        .target(name: "VeyraSDK", dependencies: ["VeyraSoftPOS", "VeyraWallet"]),
    ]
)
