# GENERATED by the Veyra SDK release train (version 1.0.16) — do not edit here.
# CocoaPods manifest for the Veyra SDK's prebuilt framework (the same hosted zip the
# Swift Package Manager manifest pins). The artifact server is authenticated: put your
# repository credentials in ~/.netrc (machine repo.veyra.co).
#
#   pod 'VeyraKMP', :podspec => 'https://raw.githubusercontent.com/Iventure-Tech/veyra-sdk-ios/1.0.16/VeyraKMP.podspec'
Pod::Spec.new do |s|
  s.name         = "VeyraKMP"
  s.version      = "1.0.16"
  s.summary      = "Veyra SDK prebuilt framework (SoftPOS + Wallet)."
  s.homepage     = "https://github.com/Iventure-Tech/veyra-sdk-ios"
  s.license      = { :type => "Commercial", :text => "See the distribution repository README." }
  s.author       = "Veyra"
  s.platforms    = { :ios => "15.0" }
  s.source       = { :http => "https://repo.veyra.co/releases/files/VeyraKMP-1.0.16.xcframework.zip" }
  s.vendored_frameworks = "VeyraKMP.xcframework"
end
